### ISSUE TITLE
Custom shared preferences name is not supported

### ISSUE THREAD

**Issue by henrichg** [ferrannp/material-preferences#13]
In my code in PreferenceFragment.onCreate():

```
    prefMng = getPreferenceManager();
    prefMng.setSharedPreferencesName("peferenceName");
    prefMng.setSharedPreferencesMode(Activity.MODE_PRIVATE);
```

This not working. Preference views are not set to values from shared preference "preferenceName".
But values in "preferenceName" are changed.

**Comment by wiyarmir** [comment]
Hi @henrichg, 

Those calls should be made before `addPreferencesFromResource()` is called. Thus, if you call it after the `super.onCreate()`, it will not have the desired effect.

Not sure on the implications of doing it before `super.onCreate()`, but what I would do is something similar to

``` java
@Override
public void addPreferencesFromResource(int preferencesResId) {
    getPreferenceManager().setSharedPreferencesName(YOUR_PREFERENCES_NAME);
    super.addPreferencesFromResource(preferencesResId);
}
```

in your custom `PreferenceFragment`

Give it a try and let me know.

**Comment by henrichg** [comment]
Hm, before super.onCreate(), getPreferenceManager() returns null.

**Comment by wiyarmir** [comment]
As one would expect. The possible solution is the snippet, please give it a
try :)

**Comment by henrichg** [comment]
Sorry,

``` @Override
public void addPreferencesFromResource(int preferencesResId) {
    getPreferenceManager().setSharedPreferencesName(YOUR_PREFERENCES_NAME);
    super.addPreferencesFromResource(preferencesResId);
}
```

working.

Thak you.
