### ISSUE TITLE
Non-transparent shadow

### ISSUE THREAD

**Issue by tirprox** [ferrannp/material-preferences#5]
Hi! Thanks for this nice lib! Shadow under the toolbar is not transparent. I have found a fix - in a file mp_activity_settings.xml you need to change this part 
<FrameLayout
        android:id="@+id/content"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_below="@id/toolbar_shadow">

to this:
<FrameLayout
        android:id="@+id/content"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_below="@id/toolbar">

I used this snippet as a temporary solution in my code (SettingsActivity.onCreate):

FrameLayout layout = (FrameLayout) findViewById(R.id.content);
        RelativeLayout.LayoutParams params = (RelativeLayout.LayoutParams) layout.getLayoutParams();
        params.addRule(RelativeLayout.BELOW, R.id.toolbar);
        layout.setLayoutParams(params);

**Comment by ferrannp** [comment]
I just published version 0.1.4. I changed the way to show that shadow so that should be fixed.
